In [48]:
import pandas as pd
import nltk
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [49]:
ppr_train = pd.read_csv("../../dataset/PreprocessedLiar/train.csv")
ppr_test = pd.read_csv("../../dataset/PreprocessedLiar/test.csv")

In [50]:
ppr_train

,articleId,cleaned_statement,label
0,2635,say annies list political group support trimes...,false
1,10540,decline coal start started natural took starte...,half-true
2,324,hillary clinton agrees john mccain voting geor...,mostly-true
3,1123,health care reform legislation likely mandate ...,false
4,9028,economic turnaround started term crist said ec...,half-true
...,...,...,...
10235,5473,larger number shark attack florida case voter ...,mostly-true
10236,3408,democrat party atlanta metro area black romney...,mostly-true
10237,3959,say alternative social security operates galve...,half-true
10238,2253,lifting cuban embargo allowing travel cuba che...,false
10239,1155,department veteran affair manual telling veter...,pants-fire

Lammetizing Text with Verb

In [51]:
def Lammetize(text):
    word_list = nltk.word_tokenize(text)
    lammetized_output = ' '.join([lemmatizer.lemmatize(w, 'v') for w in word_list])

    return lammetized_output

In [58]:
ppr_train['cleaned_statement'] = ppr_train['cleaned_statement'].apply(Lammetize)
ppr_test['cleaned_statement'] = ppr_test['cleaned_statement'].apply(Lammetize)

In [60]:
ppr_train.sample(10)

,articleId,cleaned_statement,label
9544,4705,barack obamas watch expend billion liberate pe...,pants-fire
3778,8693,dont people play game dont win play video lott...,false
4151,9314,say justin amash vote democrat republican perr...,false
8426,2127,step plan create job year vote offer drug disc...,mostly-true
3161,12692,say gary farmer claim receive absolute spokesm...,true
1173,3484,say milwaukee county park director black recei...,mostly-true
2875,5632,president barack obama reduce cost prescriptio...,true
10059,2331,state federal government gallon tax company wo...,half-true
3587,2084,health care number go layoff attrition latest ...,barely-true
7715,16,china japan surpass japanese car get average m...,half-true

In [61]:
ppr_train.to_csv(r'train2.csv', index = False)
ppr_test.to_csv(r'test2.csv', index = False)